<a href="https://colab.research.google.com/github/sapnasingh4852-source/python-DATA-science/blob/main/lec05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1

In [2]:
import numpy as np

In [3]:
# create a 5*5 matrix of random  integers(1-90)
matrix = np.random.randint(1, 91, size=(5, 5))
print(matrix)


[[67 62 79 59 83]
 [63 50  5 70 81]
 [54 30 71 85 68]
 [71 17  9 15 81]
 [74 49 49 83  6]]


In [5]:
# find mean of vaues row and colum wise

row_mean = np.mean(matrix, axis = 1)
col_mean = np.mean(matrix, axis = 0)

print ("row wise mean", row_mean)
print ("colum wise mean",col_mean)

row wise mean [70.  53.8 61.6 38.6 52.2]
colum wise mean [65.8 41.6 42.6 62.4 63.8]


In [6]:
# replace all even numbers with -1

matrix [matrix % 2 == 0] = -1
print(matrix)

[[67 -1 79 59 83]
 [63 -1  5 -1 81]
 [-1 -1 71 85 -1]
 [71 17  9 15 81]
 [-1 49 49 83 -1]]


In [7]:
# sort the array row and column wise

sorted_matrix = np.sort(matrix, axis = 1)
print(sorted_matrix)

sorted_matrix = np.sort(matrix, axis = 0)
print(sorted_matrix)

[[-1 59 67 79 83]
 [-1 -1  5 63 81]
 [-1 -1 -1 71 85]
 [ 9 15 17 71 81]
 [-1 -1 49 49 83]]
[[-1 -1  5 -1 -1]
 [-1 -1  9 15 -1]
 [63 -1 49 59 81]
 [67 17 71 83 81]
 [71 49 79 85 83]]


In [8]:
#find row and column wise sum separately

row_sum = np.sum(matrix, axis =1)
print(row_sum)

col_sum = np.sum(matrix, axis = 0)
print(col_sum)

[287 147 153 193 179]
[199  63 213 241 243]


In [10]:
# count the number of -ve's in each column
count_negatives = np.sum(matrix < 0, axis = 0)
print(count_negatives)

[2 3 0 1 2]


In [ ]:
# where method to count negative
count_negatives = np.where(matrix < 0, 1, 0)
print(count_negatives)


In [11]:
import numpy as np

In [ ]:
#invenrory control syatem
#tasks

In [13]:
# create a 5*5 array (stock levels) range 20 - 80
stock_matrix = np.random.randint(20, 81, size=(5, 5))
print(stock_matrix)

[[23 58 74 55 34]
 [68 21 79 43 25]
 [43 80 42 61 75]
 [67 73 51 32 79]
 [57 47 51 52 27]]


In [18]:
# create another 5*5 array(demand)

demand_matrix = np.random.randint( 20,81, size=(5, 5))
print(demand_matrix)

[[80 24 32 80 29]
 [21 23 77 80 48]
 [60 64 63 27 75]
 [78 23 75 73 24]
 [33 76 53 53 56]]


In [19]:
#compute
remanining_stock = stock_matrix - demand_matrix
print(remanining_stock)

[[-57  34  42 -25   5]
 [ 47  -2   2 -37 -23]
 [-17  16 -21  34   0]
 [-11  50 -24 -41  55]
 [ 24 -29  -2  -1 -29]]


In [21]:
# replace

# negative values --> 0 (out of stock)
remanining_stock = np.where(remanining_stock < 0,0, remanining_stock)
print( remanining_stock)

[[ 0 34 42  0  5]
 [47  0  2  0  0]
 [ 0 16  0 34  0]
 [ 0 50  0  0 55]
 [24  0  0  0  0]]


In [22]:
# find
# total storage
total_storage = np.sum(stock_matrix)
print(total_storage)

1317


In [26]:
# product with zero stock
product_zero_stock = np.sum(np.where(remanining_stock < 0, 1, 0), axis = 0)
print(product_zero_stock)

[0 0 0 0 0]


In [27]:
# sort each row based on remaining stock

sorted = np.sort(remanining_stock, axis = 1)
print(sorted)

[[ 0  0  5 34 42]
 [ 0  0  0  2 47]
 [ 0  0  0 16 34]
 [ 0  0  0 50 55]
 [ 0  0  0  0 24]]
