<a href="https://colab.research.google.com/github/sapnasingh4852-source/python-DATA-science/blob/main/lect04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
a = np.array([1,3,0,9,'hello'])
print(a)

['1' '3' '0' '9' 'hello']


In [12]:
np_arr= np.array([3,3,3,3,3.3,'hello',False])
print(np_arr)



['3' '3' '3' '3' '3.3' 'hello' 'False']


In [13]:
a = np.arange(3,12,1)
b = np.linspace(3,12,4,dtype = int)

print(b)

[ 3  6  9 12]


In [14]:
 a = np.array([1,2,3,4])
 b = np.array([6,7,8,9])

 print(a*2)
 print(a+b)
 print(a-b)
 print(a*b)
 print(a/b)

[2 4 6 8]
[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[0.16666667 0.28571429 0.375      0.44444444]


In [15]:
a = np.random.randint(2,15,6)
print(a)

b = a.reshape((3,2))
print(b)

[ 2  9  6  9  3 14]
[[ 2  9]
 [ 6  9]
 [ 3 14]]


In [16]:
a = np.random.randint(2,15,6)
print(a)

b = a.reshape((2,3))
print(b)

print(b.transpose())





[9 9 4 6 8 6]
[[9 9 4]
 [6 8 6]]
[[9 6]
 [9 8]
 [4 6]]


In [17]:
a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)

print(np.concatenate(( a,b)))

[13  6  3  4 14 11  1  2 13  9  2 10]


In [19]:
a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)
c = (b> 2 , b , )

In [20]:
a = np.zeros((2, 3, 4),dtype=int)
print(a)
print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [21]:
a = np.ones((2, 3, 4),dtype=int)
print(a)
print(type(a[0][0][0]))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.int64'>


In [22]:
# full
a = np.full(4,5,dtype=int)
print(a)


[5 5 5 5]


In [24]:
# arange
a = np.arange(0,9,2,dtype=int)
print(a)


[0 2 4 6 8]


In [25]:
# linspace
a = np.linspace(3, 12, 4, dtype=int)
print(a)

[ 3  6  9 12]


In [26]:
 #Shape and Size of 1-D array
a = np.arange(0,9,2,dtype=int)
print(a.shape)
print(a.size)

(5,)
5


In [27]:
# Shape and Size of 2-D array
a = np.ones((2, 3),dtype=int)
print(a.shape)
print(a.size)


(2, 3)
6


(2, 3)

In [28]:
# Random Number Generation
a = np.random.randint(0,9,2)
print(a)


[3 2]


In [29]:
a = np.random.choice([1,7,4],2)
print(a)


[7 4]


In [30]:
# Broadcasting
a = np.array([1,2,3,4])
b = np.array([9,3,4,6])
print(a*2)
print(a+b)
print(a*b)
print(a/b)
print((2*a)+b)


[2 4 6 8]
[10  5  7 10]
[ 9  6 12 24]
[0.11111111 0.66666667 0.75       0.66666667]
[11  7 10 14]


In [31]:
# Array into Matrix
a = np.random.randint(2, 15, 6)
print(a)
print(a.reshape(2,3))
print(a.reshape(3,2))

[5 2 6 3 5 2]
[[5 2 6]
 [3 5 2]]
[[5 2]
 [6 3]
 [5 2]]


In [32]:
# Transpose
a = np.random.randint(2, 15, 6)
print(a)
b = a.reshape(2,3)
print(b)
print(b.transpose())

[ 7 12  9  3 13  7]
[[ 7 12  9]
 [ 3 13  7]]
[[ 7  3]
 [12 13]
 [ 9  7]]


In [33]:
# Concatenate in 1-D array
a = np.random.randint(2, 15, 6)
print(a)
b = np.random.randint(2, 15, 6)
print(b)
print(np.concatenate((a,b)))

[ 9 13  9 11  4  9]
[ 5  4 10  2 13 14]
[ 9 13  9 11  4  9  5  4 10  2 13 14]


In [34]:
a = np.random.randint(2, 15, 6)
print(a)
b = np.random.randint(1, 15, 6)
print(b)
c = np.where(b > 2, b, a)
print(c)


[ 2  5 14  5 11  9]
[ 4  3 12 12  6  7]
[ 4  3 12 12  6  7]


In [35]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.sort(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.sort(b))


[ 3 10  2 10  8  9]
[ 2  3  8  9 10 10]
[ 6  4  3 12  7  8]
[ 3  4  6  7  8 12]


In [36]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.sum(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.sum(b))

[ 8 13 14  4  2  8]
49
[11  3  4  2  4  8]
32


In [37]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.mean(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.mean(b))

[ 6 14 14 11  8  5]
9.666666666666666
[ 7 12 12  3  4 12]
8.333333333333334


In [38]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.std(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.std(b))

[ 8 14  6  8 11  3]
3.4960294939005054
[14 13 13 14 13  9]
1.699673171197595


In [39]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.min(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.max(b))

[ 9  2  4  9 11  8]
2
[12  9  5  2  7  6]
12


In [40]:
a = np.random.randint(2, 15, 6)
print(a)
print(np.unique(a))
b = np.random.randint(2, 15, 6)
print(b)
print(np.unique(b))

[ 4 12  6  4  4  9]
[ 4  6  9 12]
[ 2  5  2 13  5  7]
[ 2  5  7 13]


In [ ]:
a = np.random.randint(2, 15, 6)
print(a)
c = a.reshape(2, 3)
b = np.random.randint(2, 15, 6)
print(b)
d = b.reshape(3, 2)
print(np.matmul(c,d))
scores = []
days = []
for i in range(0,7,1) :
 runs = input(np.array(()))
# balls = input(np.array())
# print(balls)
scores = input().split()
print(scores)
scores = [int(x) for x in scores]
print(scores)

[ 4  3 13 13  5  8]
[ 7  3 10  5 14  3]
[[240  66]
 [253  88]]
[]2,4
